[dependencies]
cuda-version = ">=12.9,<13"
ninja = ">=1.13.2,<2"
pytorch-gpu = ">=2.9.1,<3"
numba = ">=0.63.1,<0.64"
scipy = "*"
cuda = { version = ">=12.9.1,<13", channel = "nvidia" }
pytest = ">=9.0.2,<10"
pytest-cov = ">=7.0.0,<8"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.8,<4"

[workspace]
authors = ["Chin-Yun Yu <chin-yun.yu@qmul.ac.uk>"]
channels = ["https://prefix.dev/conda-forge", "nvidia"]
name = "philtorch"
platforms = ["linux-64"]

[system-requirements]
cuda = "13.0"

[pypi-dependencies]
torchlpc = ">=0.7.2, <0.8"
philtorch = { path = ".", editable = true }


[pypi-options]
no-build-isolation = true

